// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_sunny28.Models;

namespace Mission6_sunny28.Migrations
{
    [DbContext(typeof(MovieContex))]
    [Migration("20230213042410_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_sunny28.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Action/Adventure",
                            Director = "Ryan Coogler",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Black Panther",
                            Year = 2018
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Musical/Romance",
                            Director = "Joel Schumacher",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "The Phantom of the Opera",
                            Year = 2005
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Mystery/Animation",
                            Director = "Yasuichiro Yamamoto",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Detective Conan: Full Score of Fear",
                            Year = 2008
                        },
                        new
                        {
                            MovieId = 4,
                            Category = "Romance/Fantasy",
                            Director = "Makoto Shinkai",
                            Edited = false,
                            Rating = "PG",
                            Title = "Your Name.",
                            Year = 2016
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
